export const copy = {
  appName: 'Finance',
  tagline: 'Na tem računalniku. Za študente.',
  loading: 'Nalaganje…',
  dismiss: 'Zapri',
  add: 'Dodaj',
  save: 'Shrani',
  cancel: 'Prekliči',
  delete: 'Izbriši',
  edit: 'Uredi',
  manage: 'Uredi',
  income: 'Prihodek',
  expense: 'Strošek',
  all: 'Vse',
  overdue: 'Zapadlo',
  asap: 'Čim prej',
  more: 'Več',
  cantReachMac: 'Maca ni mogoče doseči. Je Finance odprt in Tailscale vklopljen?',
  somethingWrong: 'Nekaj je šlo narobe.',
  nav: {
    overview: 'Pregled',
    transactions: 'Promet',
    car: 'Avto',
    apartment: 'Stanovanje',
    shopping: 'Nakup',
    bills: 'Računi',
    debts: 'Dolgovi',
    dohodnina: 'Dohodnina',
    settings: 'Nastavitve'
  },
  overview: {
    title: 'Ta mesec',
    in: 'Dobim',
    out: 'Gre',
    leftover: 'Ostane',
    leftoverHint: 'To ti ostane, ko so servis, štipendija in računi notri.',
    stillDue: 'Še zapade',
    where: 'Kam je šlo',
    noSpend: 'Še ni stroškov',
    noSpendBody: 'Dodaj kavico, hrano ali fitnes — tu vidiš razrez.',
    addTx: 'Dodaj promet',
    billsSoon: 'Kmalu zapade',
    allBills: 'Vsi računi',
    noBillsSoon: 'V naslednjih 14 dneh nič ne zapade.',
    yearly: 'Enkrat na leto',
    debts: 'Dolgovi',
    noDebts: 'Ni zabeleženih dolgov.',
    stillOwed: 'Še dolguješ',
    nextPays: 'Naslednja plačila',
    due: 'Zapade'
  },
  onboard: {
    title: 'Tri številke, pa veš, kaj ti ostane',
    body: 'Zadnji servis, štipendija če jo imaš, in najemnina. Ostalo dodaš kasneje. Nič ne gre v oblak.',
    servis: 'Zadnji študentski servis (€)',
    stipendija: 'Štipendija (€) — lahko izpustiš',
    rent: 'Najemnina na mesec (€) — lahko izpustiš',
    rentDue: 'Kdaj zapade najemnina',
    start: 'Pokaži, kaj mi ostane',
    skip: 'Preskoči, vnesem sam'
  },
  form: {
    name: 'Ime',
    amount: 'Znesek',
    date: 'Datum',
    notes: 'Opomba',
    category: 'Kategorija',
    repeats: 'Ponavljanje',
    nextDue: 'Naslednjič',
    yearlyDate: 'Datum vsako leto',
    active: 'Aktiven',
    kind: 'Vrsta',
    color: 'Barva',
    weekly: 'Tedensko',
    monthly: 'Mesečno',
    yearly: 'Enkrat na leto',
    yearlyRoll: 'Ko označiš plačano, se datum premakne za eno leto.',
    untilDate: 'Do datuma',
    due: 'Zapadlost'
  },
  tx: {
    title: 'Promet',
    blurb: 'Servis, štipendija in poraba za izbrani mesec.',
    category: 'Kategorija',
    empty: 'Ta mesec še ni vpisov',
    emptyBody: 'Dodaj servis ali uvozi Revolut CSV. Knjige ostanejo na Macu.',
    add: 'Dodaj vpis',
    newTitle: 'Nov vpis',
    editTitle: 'Uredi vpis',
    amount: 'Znesek',
    date: 'Datum',
    payee: 'Kdo / kje',
    notes: 'Opomba',
    confirmDelete: 'Izbrišem ta vpis?',
    import: 'Uvozi Revolut',
    importOk: (n: number, skipped: number) =>
      skipped > 0 ? `Uvoženih ${n} vrstic z Revoluta (${skipped} preskočenih).` : `Uvoženih ${n} vrstic z Revoluta.`,
    importNone: 'V datoteki ni bilo zaključenih EUR vrstic.',
    importBad: 'To ne izgleda kot Revolut CSV.'
  },
  bills: {
    title: 'Računi',
    blurb: 'Fitnes, band, najemnina. Avto in stanovanje imata svoja zavihka, ko ju dodaš.',
    empty: 'Še ni računov',
    emptyBody: 'Dodaj mesečni strošek ali letnega (vinjeta, zavarovanje).',
    addYearly: 'Dodaj letnega',
    addBill: 'Dodaj račun',
    monthlyWeekly: 'Mesečno in tedensko',
    noRepeating: 'Ni mesečnih ali tedenskih računov.',
    yearly: 'Enkrat na leto',
    noYearly: 'Ni letnih stroškov. Sem gre registracija, zavarovanje, vinjeta.',
    archived: 'Neaktivni',
    markPaid: 'Označi plačano',
    edit: 'Uredi račun',
    newBill: 'Nov račun',
    yearlyTitle: 'Letno plačilo',
    pay: (name: string) => `Plačaj ${name}`,
    deleteConfirm: (name: string) => `Izbrišem ${name}? Plačila ostanejo v Prometu.`,
    yearlyPlaceholder: 'Avto – registracija'
  },
  debts: {
    title: 'Dolgovi',
    blurb: 'Razdeli saldo — npr. 350 € čim prej, potem 125 € po mesecih.',
    empty: 'Še ni dolgov',
    emptyBody: 'Dodaj saldo, potem ga razdeli na obroke.',
    add: 'Dodaj dolg',
    paidOff: 'Poplačano',
    planned: 'načrtovano',
    noPlan: 'Še ni obrokov',
    leftToPlan: 'še za razdeliti',
    apr: 'Obresti',
    payoff: 'Poplačilo',
    done: 'Končano',
    wontPay: 'S tem tempom se ne poplača',
    years50: 'Več kot 50 let',
    mo: 'mes.',
    pay: 'Plačaj',
    addPayment: 'Dodaj obrok',
    logOther: 'Drug znesek',
    edit: 'Uredi dolg',
    newDebt: 'Nov dolg',
    totalOwed: 'Celoten saldo',
    splitHelp: 'Potem na kartici razdeli saldo na obroke.',
    minPay: 'Min. obrok',
    extra: 'Dodatno',
    payCategory: 'Kategorija plačila',
    editPayment: 'Uredi obrok',
    addPaymentTitle: (name: string) => `Obrok · ${name}`,
    notPlanned: 'še ni razdeljeno',
    paidOn: 'Plačano',
    logPayment: 'Zabeleži plačilo',
    removePlan: 'Odstranim ta obrok?',
    deleteConfirm: (name: string) => `Izbrišem ${name}? Plačila ostanejo v Prometu.`,
    payName: (name: string) => `Plačaj ${name}`,
    total: 'Skupaj'
  },
  cats: {
    edit: 'Uredi kategorijo',
    new: 'Nova kategorija',
    deleteConfirm: (name: string) => `Izbrišem ${name}?`
  },
  area: {
    car: 'Avto',
    carBlurb: 'Kredit in vse za avto — registracija, zavarovanje, servis.',
    apartment: 'Stanovanje',
    apartmentBlurb: 'Skupni stroški. Kdor vpiše, je plačal — deli se enako.'
  },
  apt: {
    balances: 'Kdo komu dolguje',
    youOwe: (name: string) => `Dolguješ ${name}`,
    theyOwe: (name: string) => `${name} ti dolguje`,
    even: 'Vsi saldi so 0.',
    evenWith: (name: string) => `S ${name} sta poravnana.`,
    add: 'Dodaj strošek',
    list: 'Skupni stroški',
    empty: 'Še ni skupnih stroškov',
    emptyBody: 'TV, najemnina, pohištvo — vpiši tukaj, ne v Promet.',
    paidBy: 'Plačal',
    share: 'delež',
    settle: 'Poravnaj',
    settleTitle: (name: string) => `Poravnava · ${name}`,
    settleHelp: 'Znesek, ki ti ga vrnejo. Ne deli se.',
    needPeople: 'V Nastavitvah dodaj sostanovalce. Potem se stroški delijo.',
    splitHint: (n: number) => `Deli se na ${n} ${n === 1 ? 'osebo' : 'oseb'}.`,
    deleteConfirm: (name: string) => `Izbrišem ${name}? Saldi se preračunajo.`
  },
  shop: {
    title: 'Nakup',
    blurb: 'Skupni seznam. Ko kupiš, označi stvari in vpiši znesek — deli se enako kot Stanovanje.',
    toBuy: 'Za kupiti',
    bought: 'Kupljeno',
    add: 'Dodaj stvar',
    iBought: 'Sem kupil',
    empty: 'Seznam je prazen',
    emptyBody: 'Mleko, kruh, čistilo — vsi v gospodinjstvu vidijo isto.',
    addedBy: (name: string) => `dodal ${name}`,
    boughtBy: (name: string) => `kupil ${name}`,
    pick: 'Kaj si kupil?',
    needItems: 'Izberi vsaj eno stvar.',
    deleteConfirm: (name: string) => `Odstranim ${name} s seznama?`,
    buyHelp: 'Znesek z blagajne. Deli se na vse v gospodinjstvu.'
  },
  house: {
    title: 'Gospodinjstvo',
    blurb: 'Stanovanje in nakup sta skupna. Vsak ima svojo kodo za telefon.',
    yourName: 'Tvoje ime',
    add: 'Dodaj člana',
    memberName: 'Ime',
    token: 'Koda za telefon',
    rotate: 'Nova koda',
    rotateConfirm: 'Stari telefon tega člana neha delati, dokler ne prilepiš nove kode.',
    remove: 'Odstrani',
    removeConfirm: (name: string) => `Odstranim ${name}? Saldo v Stanovanju mora biti 0.`,
    host: 'Gostitelj',
    you: 'ti'
  },
  dohodnina: {
    title: 'Dohodnina',
    blurb:
      'Ocena iz tvojega študentskega in drugega dohodka letos. Ni FURS in nisi davčni svetovalec — za obračun vprašaj starše ali računovodjo.',
    ytd: 'Na izplačila do zdaj',
    projected: 'Če enako do decembra',
    paidThisYear: 'Letos prejeto',
    payments: 'izplačil',
    yearOver: 'Leto je končano — isto kot do zdaj.',
    lastYear: 'Lani (model)',
    lastYearHelp:
      'Pri študentskem delu je olajšava pogosto dovolj, da je davek 0. Če si lani kaj plačal, vpiši številke z informacije o odmeri — prispevki in stroški se letos prilagodijo tvojemu servisu.',
    dohodek: 'Dohodek',
    prispevki: 'Prispevki',
    stroski: 'Stroški',
    olajsava: 'Olajšava',
    paid: 'Plačana dohodnina',
    osnova: 'Osnova',
    save: 'Shrani lani',
    print: 'Natisni oceno',
    printTitle: 'Ocena dohodnine',
    quietYear: 'Letos si pod olajšavo — ocena je 0 €. Če bo servis šel gor, se to spremeni.',
    disclaimer: 'To ni informacija o odmeri. FURS šteje dokončno. Knjige so samo na tem Macu.'
  },
  settings: {
    title: 'Nastavitve',
    blurb: 'Vse ostane v lokalni SQLite datoteki na Macu.',
    prefs: 'Nastavitve',
    currency: 'Valuta',
    monthStart: 'Mesec se začne na dan',
    categories: 'Kategorije',
    incomeCats: 'Prihodki',
    expenseCats: 'Stroški',
    phone: 'Telefon',
    phoneHelp:
      'Isti pregled na telefonu čez Tailscale. Safari (Dodaj na začetni zaslon) ali aplikacija. Finance mora ostati odprt. Promet ne gre v javni internet. Vrata',
    safariHelp:
      'Na iPhonu: najprej Dodaj na začetni zaslon, potem odpri ikono in vpiši kodo. Ni App Store in ni podpisa.',
    safariUrl: 'Naslov v Safariju',
    safariNeedHost: 'Vpiši Tailscale ime zgoraj, da dobiš naslov za Safari.',
    allowPhone: 'Dovoli dostop s telefona',
    keepAwake: 'Naj Mac ne zaspi, dokler je dostop vklopljen',
    listening: 'Telefon se lahko poveže.',
    portBusy: 'Vklopljeno, vendar vrata niso odprta.',
    off: 'Izklopljeno.',
    host: 'Gostitelj za telefon',
    token: 'Koda za povezavo',
    copy: 'Kopiraj',
    newToken: 'Nova koda',
    rotateConfirm: 'Stari telefoni nehajo delati, dokler ne prilepiš nove kode.',
    thisPhone: 'Ta telefon',
    thisPhoneHelp: 'Bereš knjige z Maca. Tukaj ni shranjeno nič.',
    changePair: 'Drug Mac',
    forgetConfirm: 'Pozabim ta Mac? Gostitelja in kodo vpišeš znova.',
    useTailscale: 'Uporabi Tailscale ime'
  },
  phoneGate: {
    title: 'Poveži z Macom',
    body: 'Tailscale na telefonu in Macu, isti račun. Na Macu: Nastavitve → Telefon, potem prilepi gostitelja in kodo.',
    bodySafari:
      'Si že na Macu čez Tailscale. Prilepi kodo iz Nastavitve → Telefon — ali kodo člana iz Gospodinjstva.',
    host: 'Gostitelj',
    token: 'Koda',
    connect: 'Poveži',
    checking: 'Preverjam…',
    cant: 'Maca ni mogoče doseči',
    cantBody: 'Odpri Finance na Macu, naj ne zaspi, in preveri Tailscale na obeh.',
    retry: 'Poskusi znova',
    retrying: 'Poskušam…',
    change: 'Drug gostitelj ali koda',
    changeToken: 'Druga koda',
    reaching: 'Iščem Mac…'
  }
} as const

export const DOMAIN_LABELS_SL = {
  personal: 'Osebno',
  car: 'Avto',
  apartment: 'Stanovanje'
} as const
